server:
  port: 8443

spring:
  application:
    name: evaluacion-tecnica
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth
    username: sa
    password: 111111

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 86400
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%12.12t] %clr(%-50.50logger{49}){cyan} [%5.5L] : %m%n%wEx'
  level:
    root: info
    com.dqv5: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

load:
  system:
    log: true
  roles:
    - roleValue: ROLE_ADMIN
      roleName: rol normal
  users:
    - username: admin
      password: 123456
      nickName: Tecnico
      role: ROLE_ADMIN

